version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_NODE_BASE_URL=http://host.docker.internal:5000  
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - VITE_DB_URL=mongodb://mongo:27017/EventManagmentApp
      - JWT_SECRET_KEY=EventManagementAppJWT
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
